### ISSUE TITLE
Add tieflings to the race package

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/world#11]
Add tieflings to the race package here: https://github.com/ironarachne/world/tree/master/pkg/race

Reference the D&D 5E version of tieflings.

**Comment by BenOvermyer** [comment]
This link provides some data on height and weight: http://legacy.aonprd.com/advancedRaceGuide/ageHeightWeight.html

**Comment by smortime** [comment]
Hey @BenOvermyer, I'll take a shot at this if alright with you.

**Comment by BenOvermyer** [comment]
@smortime All yours.
