### ISSUE TITLE
Replace Animal struct with Species

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/world#12]
Currently, the animal package uses its own structure - Animal. Replace this with the Species struct defined in the species package, and convert all animals to use the new struct.

This will require touching the climate package also, as it consumes the animal package.

Adding appropriate traits is outside the scope of this issue. However, all resources need to make the transition.

**Comment by shade34321** [comment]
I'd like to take a crack at this.

**Comment by BenOvermyer** [comment]
@shade34321 All yours.

**Comment by shade34321** [comment]
Sweet, I'll take a look at it this tonight and see what I can do. Thanks!

**Comment by shade34321** [comment]
Hey, quick question. I saw the `species` struct but the I noticed the fields within the `animal` and `species` struct don't match up. Is there something I can look at within the project that can help point me in the right direction? Thanks!

**Comment by BenOvermyer** [comment]
All of the following properties of the `Animal` struct can be discarded as part of the migration:

```
AnimalType     string
EatsAnimals    bool
EatsPlants     bool
IsAquatic      bool
IsMount        bool
IsPackAnimal   bool
IsScavenger    bool
```

The others should have parity with the `Species` struct.

**Comment by BenOvermyer** [comment]
@shade34321 how's this going?

**Comment by shade34321** [comment]
Hey, I've started this but haven't made a ton of progress just yet. I'm hoping to work on it some tonight. Sorry it taking a bit.

**Comment by BenOvermyer** [comment]
No worries, just curious.
