### ISSUE TITLE
Source/License of Graphics

### ISSUE THREAD

**Issue by alecnunn** [ironarachne/world#35]
Hello, I was wondering where the graphics were obtained and what license they are under. This is an awesome tool set, just want to ensure I can fully use what is generated.

**Comment by BenOvermyer** [comment]
All of the artwork was taken from public domain sources, or created by myself.

The artwork can be used without restriction and without attribution.

I'll add something to the repository documenting this.

**Comment by alecnunn** [comment]
Awesome, thank you for clarification! Thanks for creating all of these awesome pieces of software.

**Comment by BenOvermyer** [comment]
This is live on the site now.
