### ISSUE TITLE
When trying to run says Sentry Not Set Up

### ISSUE THREAD

**Issue by yndrelbosch** [ironarachne/world#5]
What is Sentry, how do I get it / set it up, so I can run the built files from this project?

Edit, I made it work by adding 
	os.Setenv("SENTRY_DSN", "DSN Code Here")
to the main function.

**Comment by BenOvermyer** [comment]
Sentry is an error tracking service (sentry.io). It's free and is used for development.

You can disable it without code changes by setting an environment variable `SENTRY_DSN` to a non-empty string.

**Comment by BenOvermyer** [comment]
The latest version (0.6.5) makes it so that Sentry is optional.
