### ISSUE TITLE
Change organization ranks to have multiple possible age categories

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/world#8]
Currently, [organization ranks](https://github.com/ironarachne/world/blob/master/pkg/organization/types.go#L12) have only a single possible age category.

It should be possible to specify multiple possible age categories, and for the generation process to select one of them randomly when generating a member of that rank.

This should affect only the organization package.

**Comment by thejayhaykid** [comment]
I'll take a whack at this one

**Comment by BenOvermyer** [comment]
@thejayhaykid how goes the progress?

**Comment by thejayhaykid** [comment]
Hey man, I haven't had the time I had hoped to dive into this one yet. I'm sorry about that.

**Comment by BenOvermyer** [comment]
@thejayhaykid no worries. I'll take over.
