### ISSUE TITLE
Add all missing weapons from the D&D 5E player's handbook

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/world#9]
The weapons resources are listed here: https://github.com/ironarachne/world/blob/master/pkg/resource/weapons.go

This list should include at least one pattern for every weapon in the Dungeons & Dragons fifth edition Player's Handbook.

**Comment by BenOvermyer** [comment]
Relevant list here: http://www.5esrd.com/equipment/weapons/

**Comment by tpaschalis** [comment]
Hi! I'd like to start working on this if it's okay! What should the "Value" field of the Pattern struct hold?    
Should it be the cost, weight, or just a dummy value that will be edited later on?

**Comment by BenOvermyer** [comment]
@tpaschalis The Value is meant to be the cost, but right now it's only a rough estimate. A future iteration will focus on pricing and currency.

**Comment by tpaschalis** [comment]
Okay. For starter, I'll be using the Gold Piece and Silver Piece prices from the PHB, with 10:1 currency ratio,

**Comment by BenOvermyer** [comment]
> Okay. For starters, I'll be using the Gold Piece and Silver Piece prices from the PHB, with 10:1 currency ratio.

Sounds good.

**Comment by sumitb** [comment]
@tpaschalis Are you still working on it, if not I would like to take a stab at this issue cc @BenOvermyer

**Comment by tpaschalis** [comment]
Unfortunately I currently don't have the bandwidth to close the issue. Feel free to take it on if you want, and/or use the work I've currently done to close it. It shouldn't be more than half an hour of work. Best of luck!

**Comment by BenOvermyer** [comment]
@tpaschalis Thanks for your work on this! I _think_ you'll still get credit for Hacktoberfest if this PR is merged before the end of the month.
